[2024-07-22 13:47:29,068][flwr][INFO] - Starting Flower simulation, config: num_rounds=10, no round_timeout
[2024-07-22 13:47:29,974][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 7796167476.0, 'node:127.0.0.1': 1.0, 'CPU': 12.0, 'object_store_memory': 2147483648.0, 'node:__internal_head__': 1.0}
[2024-07-22 13:47:29,975][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-07-22 13:47:29,975][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0}
[2024-07-22 13:47:29,981][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 6 actors
[2024-07-22 13:47:29,982][flwr][INFO] - [INIT]
[2024-07-22 13:47:29,982][flwr][INFO] - Requesting initial parameters from one random client
[2024-07-22 13:47:31,402][flwr][INFO] - Received initial parameters from one random client
[2024-07-22 13:47:31,402][flwr][INFO] - Evaluating initial global parameters
[2024-07-22 13:47:31,716][flwr][ERROR] - default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'torch.utils.data.dataset.Subset'>
[2024-07-22 13:47:31,718][flwr][ERROR] - Traceback (most recent call last):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/app.py", line 323, in start_simulation
    hist = run_fl(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/Users/charansr/Stamp2024/server.py", line 80, in evaluate_fn_mlp
    trainloss, trainaccuracy, trainprecision, trainrecall, trainf1, trainconf_matrix = test(model, trainloader, device)
  File "/Users/charansr/Stamp2024/model.py", line 65, in test
    for data in testloader:
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 191, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'torch.utils.data.dataset.Subset'>

[2024-07-22 13:47:31,718][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
